version: '3.4'

services:

  nessie:
    image: projectnessie/nessie:latest
    container_name: nessie
    ports:
      - 19120:19120    
    networks:
      - lbe-iceberg
  

networks:
  lbe-iceberg:
    external: true
