version: '3.4'

services:

  spark-master:
    image: spark-master
    container_name: spark-master
    networks:
      - lbe-iceberg
    ports:
      - "8081:8080"
      - "7077:7077"

  spark-worker:
    image: spark-worker
    depends_on:
      - spark-master
    container_name: spark-worker
    networks:
      - lbe-iceberg
    ports:
      - "8082:8081"
  

networks:
  lbe-iceberg:
    external: true
